In [1]:
%pylab inline

import networkx as nx
import scipy.sparse
from sklearn.datasets import make_sparse_spd_matrix

import regain; reload(regain)
from regain.datasets import is_pos_def, is_pos_semidef
from regain.datasets import generate_ma_xue_zou
from regain.plot import plot_graph_with_latent_variables

from scipy.io import loadmat
from sklearn.utils.extmath import squared_norm

Populating the interactive namespace from numpy and matplotlib


In [2]:
import pandas as pd
data = pd.read_csv("/home/fede/src/slipguru/regain/regain/data/gene_chandrasekaran.csv").values.T

In [3]:
C = loadmat("../regain/data/X_output_chandra.mat")['X1']
C2 = loadmat("../regain/data/X2_output_chandra.mat")['X2']
out_B = loadmat("../regain/data/out_B.mat")
Sigma0 = loadmat("../regain/data/Sigma0.mat")['SigmaO']

In [4]:
rho = 0.0313

In [5]:
n_dim = 200

In [6]:
idx = np.argsort(data.var(0))[::-1][:n_dim]

In [7]:
Sigma = np.cov(data[:, idx].T)

In [198]:
from regain import prox; reload(prox);
from regain.admm import latent_time_graph_lasso_; reload(latent_time_graph_lasso_)
from regain.admm import latent_time_graph_lasso_v2_; reload(latent_time_graph_lasso_v2_)

from regain.admm import time_graph_lasso_; reload(time_graph_lasso_)
ret = latent_time_graph_lasso_.time_latent_graph_lasso(
        np.array([Sigma0]), alpha=0.05, tau=0.25,
        tol=1e-5, rtol=1e-5, rho=1./ Sigma0.shape[0], eta=0, beta=0,
        verbose=1, max_iter=500)
# ret = time_graph_lasso_.time_graph_lasso([data[:, idx]], rho=rho, beta=5*rho, tol=1e-6,
#                                                        verbose=1, max_iter=100)

obj: -42.6730, rnorm: 57.2539, snorm: 0.0267,eps_pri: 0.0020, eps_dual: 0.0014
obj: -42.6690, rnorm: 29.8840, snorm: 0.4705,eps_pri: 0.0020, eps_dual: 0.0014
obj: -42.6063, rnorm: 29.6614, snorm: 0.0242,eps_pri: 0.0020, eps_dual: 0.0014
obj: -40.1100, rnorm: 27.7469, snorm: 0.0707,eps_pri: 0.0020, eps_dual: 0.0014
obj: -35.3218, rnorm: 25.4508, snorm: 0.0906,eps_pri: 0.0020, eps_dual: 0.0014
obj: -32.3591, rnorm: 24.2532, snorm: 0.0622,eps_pri: 0.0020, eps_dual: 0.0014
obj: -30.5446, rnorm: 23.5128, snorm: 0.0437,eps_pri: 0.0020, eps_dual: 0.0014
obj: -28.4146, rnorm: 22.7027, snorm: 0.0445,eps_pri: 0.0020, eps_dual: 0.0014
obj: -25.0830, rnorm: 21.5648, snorm: 0.0508,eps_pri: 0.0020, eps_dual: 0.0014
obj: -20.5132, rnorm: 20.1943, snorm: 0.0567,eps_pri: 0.0020, eps_dual: 0.0014
obj: -14.9684, rnorm: 18.6272, snorm: 0.0616,eps_pri: 0.0020, eps_dual: 0.0014
obj: -9.8406, rnorm: 17.1348, snorm: 0.0615,eps_pri: 0.0020, eps_dual: 0.0014
obj: -3.9617, rnorm: 15.5832, snorm: 0.0595,eps_pri: 

obj: 38.9779, rnorm: 0.4151, snorm: 0.0005,eps_pri: 0.0020, eps_dual: 0.0015
obj: 38.9863, rnorm: 0.4075, snorm: 0.0005,eps_pri: 0.0020, eps_dual: 0.0015
obj: 38.9972, rnorm: 0.3989, snorm: 0.0006,eps_pri: 0.0020, eps_dual: 0.0015
obj: 39.0070, rnorm: 0.3910, snorm: 0.0006,eps_pri: 0.0020, eps_dual: 0.0015
obj: 39.0137, rnorm: 0.3841, snorm: 0.0006,eps_pri: 0.0020, eps_dual: 0.0015
obj: 39.0187, rnorm: 0.3781, snorm: 0.0005,eps_pri: 0.0020, eps_dual: 0.0015
obj: 39.0256, rnorm: 0.3716, snorm: 0.0005,eps_pri: 0.0020, eps_dual: 0.0015
obj: 39.0307, rnorm: 0.3660, snorm: 0.0005,eps_pri: 0.0020, eps_dual: 0.0015
obj: 39.0369, rnorm: 0.3596, snorm: 0.0004,eps_pri: 0.0020, eps_dual: 0.0015
obj: 39.0439, rnorm: 0.3534, snorm: 0.0005,eps_pri: 0.0020, eps_dual: 0.0015
obj: 39.0603, rnorm: 0.3445, snorm: 0.0006,eps_pri: 0.0020, eps_dual: 0.0015
obj: 39.0656, rnorm: 0.3354, snorm: 0.0008,eps_pri: 0.0020, eps_dual: 0.0015
obj: 39.0696, rnorm: 0.3287, snorm: 0.0007,eps_pri: 0.0020, eps_dual: 0.0015

obj: 39.2617, rnorm: 0.0678, snorm: 0.0000,eps_pri: 0.0020, eps_dual: 0.0015
obj: 39.2620, rnorm: 0.0672, snorm: 0.0000,eps_pri: 0.0020, eps_dual: 0.0015
obj: 39.2623, rnorm: 0.0666, snorm: 0.0000,eps_pri: 0.0020, eps_dual: 0.0015
obj: 39.2627, rnorm: 0.0659, snorm: 0.0000,eps_pri: 0.0020, eps_dual: 0.0015
obj: 39.2630, rnorm: 0.0653, snorm: 0.0000,eps_pri: 0.0020, eps_dual: 0.0015
obj: 39.2633, rnorm: 0.0647, snorm: 0.0000,eps_pri: 0.0020, eps_dual: 0.0015
obj: 39.2635, rnorm: 0.0641, snorm: 0.0000,eps_pri: 0.0020, eps_dual: 0.0015
obj: 39.2638, rnorm: 0.0635, snorm: 0.0000,eps_pri: 0.0020, eps_dual: 0.0015
obj: 39.2641, rnorm: 0.0629, snorm: 0.0000,eps_pri: 0.0020, eps_dual: 0.0015
obj: 39.2644, rnorm: 0.0623, snorm: 0.0000,eps_pri: 0.0020, eps_dual: 0.0015
obj: 39.2648, rnorm: 0.0616, snorm: 0.0000,eps_pri: 0.0020, eps_dual: 0.0015
obj: 39.2650, rnorm: 0.0610, snorm: 0.0000,eps_pri: 0.0020, eps_dual: 0.0015
obj: 39.2653, rnorm: 0.0605, snorm: 0.0000,eps_pri: 0.0020, eps_dual: 0.0015

obj: 39.2832, rnorm: 0.0224, snorm: 0.0000,eps_pri: 0.0020, eps_dual: 0.0015
obj: 39.2833, rnorm: 0.0222, snorm: 0.0000,eps_pri: 0.0020, eps_dual: 0.0015
obj: 39.2833, rnorm: 0.0220, snorm: 0.0000,eps_pri: 0.0020, eps_dual: 0.0015
obj: 39.2834, rnorm: 0.0218, snorm: 0.0000,eps_pri: 0.0020, eps_dual: 0.0015
obj: 39.2834, rnorm: 0.0217, snorm: 0.0000,eps_pri: 0.0020, eps_dual: 0.0015
obj: 39.2835, rnorm: 0.0215, snorm: 0.0000,eps_pri: 0.0020, eps_dual: 0.0015
obj: 39.2836, rnorm: 0.0213, snorm: 0.0000,eps_pri: 0.0020, eps_dual: 0.0015
obj: 39.2836, rnorm: 0.0212, snorm: 0.0000,eps_pri: 0.0020, eps_dual: 0.0015
obj: 39.2837, rnorm: 0.0210, snorm: 0.0000,eps_pri: 0.0020, eps_dual: 0.0015
obj: 39.2837, rnorm: 0.0208, snorm: 0.0000,eps_pri: 0.0020, eps_dual: 0.0015
obj: 39.2838, rnorm: 0.0207, snorm: 0.0000,eps_pri: 0.0020, eps_dual: 0.0015
obj: 39.2838, rnorm: 0.0205, snorm: 0.0000,eps_pri: 0.0020, eps_dual: 0.0015
obj: 39.2839, rnorm: 0.0204, snorm: 0.0000,eps_pri: 0.0020, eps_dual: 0.0015

/home/fede/src/slipguru/regain/regain/admm/latent_time_graph_lasso_.py:444: UserWarning: Objective did not converge.
  


In [199]:
ret[0]

array([[[ 5.23523667, -0.44741678,  0.18819825, ...,  0.09278135,
         -0.1363027 , -0.28331023],
        [-0.44741678,  5.37956445, -0.05245413, ..., -0.35752682,
          0.17120644, -0.13946219],
        [ 0.18819825, -0.05245413,  6.38294449, ...,  0.38557892,
         -0.27739973, -0.        ],
        ..., 
        [ 0.09278135, -0.35752682,  0.38557892, ...,  5.8506178 ,
         -0.        ,  0.2289627 ],
        [-0.1363027 ,  0.17120644, -0.27739973, ..., -0.        ,
          5.78472854,  0.        ],
        [-0.28331023, -0.13946219, -0.        , ...,  0.2289627 ,
          0.        ,  6.27663957]]])

In [193]:
ret[0]

array([[[  2.96665419e+00,  -1.50149969e-06,   2.45594948e-06, ...,
          -4.57760955e-06,  -1.19893927e-06,   8.41208110e-07],
        [ -1.50149969e-06,   3.08477658e+00,  -9.12760732e-07, ...,
          -8.27101288e-06,  -6.24092554e-07,  -1.32170773e-06],
        [  2.45594948e-06,  -9.12760732e-07,   3.44988036e+00, ...,
           5.67057627e-06,   5.92599793e-08,  -6.60000591e-07],
        ..., 
        [ -4.57760955e-06,  -8.27101288e-06,   5.67057627e-06, ...,
           2.80470606e+00,  -1.93081382e-05,   6.47461571e-06],
        [ -1.19893927e-06,  -6.24092554e-07,   5.92599793e-08, ...,
          -1.93081382e-05,   3.04007972e+00,  -1.95566345e-06],
        [  8.41208110e-07,  -1.32170773e-06,  -6.60000591e-07, ...,
           6.47461571e-06,  -1.95566345e-06,   3.48563401e+00]]])

In [181]:
ret[0]

array([[[ 2.96665365, -0.        ,  0.        , ...,  0.        ,
         -0.        , -0.        ],
        [-0.        ,  3.08477647, -0.        , ..., -0.        ,
          0.        , -0.        ],
        [ 0.        , -0.        ,  3.4498787 , ..., -0.        ,
         -0.        , -0.        ],
        ..., 
        [ 0.        , -0.        , -0.        , ...,  2.80471091,
         -0.        ,  0.        ],
        [-0.        ,  0.        , -0.        , ..., -0.        ,
          3.04007978, -0.        ],
        [-0.        , -0.        , -0.        , ...,  0.        ,
         -0.        ,  3.48563407]]])

In [137]:
from regain import prox; reload(prox);
from regain.admm import latent_graph_lasso_; reload(latent_graph_lasso_)
ret = latent_graph_lasso_.latent_graph_lasso(Sigma0, alpha=0.05, tau=0.25,
                                             tol=1e-5, rtol=1e-5,
                                             rho=1. / Sigma0.shape[0],
                                                       verbose=1, max_iter=500)
# ret = time_graph_lasso_.time_graph_lasso([data[:, idx]], rho=rho, beta=5*rho, tol=1e-6,
#                                                        verbose=1, max_iter=100)

obj: -39.7164, rnorm: 41.0269, snorm: 0.4103,eps_pri: 0.0014, eps_dual: 0.0010
obj: -35.7734, rnorm: 16.4937, snorm: 0.0750,eps_pri: 0.0013, eps_dual: 0.0010
obj: -35.7193, rnorm: 10.2106, snorm: 0.0121,eps_pri: 0.0013, eps_dual: 0.0010
obj: -35.9820, rnorm: 9.8531, snorm: 0.0097,eps_pri: 0.0013, eps_dual: 0.0010
obj: -35.3268, rnorm: 8.9897, snorm: 0.0106,eps_pri: 0.0013, eps_dual: 0.0010
obj: -34.6391, rnorm: 8.2244, snorm: 0.0096,eps_pri: 0.0013, eps_dual: 0.0010
obj: -33.9999, rnorm: 7.5758, snorm: 0.0081,eps_pri: 0.0013, eps_dual: 0.0010
obj: -33.4009, rnorm: 7.0073, snorm: 0.0069,eps_pri: 0.0013, eps_dual: 0.0010
obj: -32.7618, rnorm: 6.4579, snorm: 0.0060,eps_pri: 0.0013, eps_dual: 0.0010
obj: -32.2318, rnorm: 6.0147, snorm: 0.0053,eps_pri: 0.0013, eps_dual: 0.0010
obj: -31.6746, rnorm: 5.5699, snorm: 0.0047,eps_pri: 0.0013, eps_dual: 0.0010
obj: -31.1410, rnorm: 5.1767, snorm: 0.0041,eps_pri: 0.0013, eps_dual: 0.0010
obj: -30.6728, rnorm: 4.8312, snorm: 0.0037,eps_pri: 0.0013, 

obj: -24.6647, rnorm: 0.0013, snorm: 0.0000,eps_pri: 0.0013, eps_dual: 0.0010


In [11]:
from regain import utils; reload(utils)

np.fill_diagonal(C, 0)
np.fill_diagonal(Kobs[0], 0)

np.fill_diagonal(C2, 0)
np.fill_diagonal(ret[1][0], 0)

In [68]:
utils.error_norm(C, Kobs[0])
utils.error_norm(C2, ret[1][0])

ValueError: operands could not be broadcast together with shapes (100,100) (200,200) 

In [26]:
np.linalg.matrix_rank(L)

7

In [35]:
np.linalg.matrix_rank(ret[1][0])

7

In [29]:
ret[1] - L

array([[[ -1.23197551e-05,  -1.57041118e-05,  -4.78362318e-06, ...,
          -6.60862967e-06,  -4.14576838e-06,  -1.83054941e-05],
        [ -1.57041118e-05,  -3.04939523e-05,   1.71615719e-05, ...,
          -2.01636458e-05,  -1.38704622e-05,  -1.61928006e-05],
        [ -4.78362318e-06,   1.71615719e-05,  -1.50897400e-06, ...,
           3.05981548e-05,   2.71441383e-05,  -2.21862007e-05],
        ..., 
        [ -6.60862967e-06,  -2.01636458e-05,   3.05981548e-05, ...,
          -1.15828419e-04,  -2.02463003e-05,   1.45002912e-06],
        [ -4.14576838e-06,  -1.38704622e-05,   2.71441383e-05, ...,
          -2.02463003e-05,  -2.97229579e-05,   2.48729414e-05],
        [ -1.83054941e-05,  -1.61928006e-05,  -2.21862007e-05, ...,
           1.45002912e-06,   2.48729414e-05,  -6.81388975e-05]]])

In [11]:
R, S, L, obj, eigR, eigL, resid, iter_ = out_B['out_B'][0][0]

In [32]:
S

array([[ 2.9667206 , -0.        ,  0.        , ...,  0.        ,
        -0.        , -0.        ],
       [-0.        ,  3.0848807 , -0.        , ..., -0.        ,
         0.        , -0.        ],
       [ 0.        , -0.        ,  3.45005447, ..., -0.        ,
        -0.        , -0.        ],
       ..., 
       [ 0.        , -0.        , -0.        , ...,  2.80496114,
        -0.        ,  0.        ],
       [-0.        ,  0.        , -0.        , ..., -0.        ,
         3.04014215, -0.        ],
       [-0.        , -0.        , -0.        , ...,  0.        ,
        -0.        ,  3.48560667]])

In [56]:
ret[0]

array([[[  2.96665419e+00,  -1.50149969e-06,   2.45594948e-06, ...,
          -4.57760955e-06,  -1.19893928e-06,   8.41208109e-07],
        [ -1.50149969e-06,   3.08477658e+00,  -9.12760732e-07, ...,
          -8.27101288e-06,  -6.24092554e-07,  -1.32170773e-06],
        [  2.45594948e-06,  -9.12760732e-07,   3.44988036e+00, ...,
           5.67057627e-06,   5.92599790e-08,  -6.60000592e-07],
        ..., 
        [ -4.57760955e-06,  -8.27101288e-06,   5.67057627e-06, ...,
           2.80470606e+00,  -1.93081382e-05,   6.47461571e-06],
        [ -1.19893928e-06,  -6.24092554e-07,   5.92599790e-08, ...,
          -1.93081382e-05,   3.04007972e+00,  -1.95566345e-06],
        [  8.41208109e-07,  -1.32170773e-06,  -6.60000592e-07, ...,
           6.47461571e-06,  -1.95566345e-06,   3.48563401e+00]]])

In [46]:
S

array([[ 2.9667206 , -0.        ,  0.        , ...,  0.        ,
        -0.        , -0.        ],
       [-0.        ,  3.0848807 , -0.        , ..., -0.        ,
         0.        , -0.        ],
       [ 0.        , -0.        ,  3.45005447, ..., -0.        ,
        -0.        , -0.        ],
       ..., 
       [ 0.        , -0.        , -0.        , ...,  2.80496114,
        -0.        ,  0.        ],
       [-0.        ,  0.        , -0.        , ..., -0.        ,
         3.04014215, -0.        ],
       [-0.        , -0.        , -0.        , ...,  0.        ,
        -0.        ,  3.48560667]])

In [115]:
Sigma0

array([[ 0.29008492,  0.02411197, -0.01403351, ..., -0.00509533,
         0.00639793,  0.00485253],
       [ 0.02411197,  0.27920974,  0.01712859, ...,  0.02282177,
         0.00047733,  0.01061766],
       [-0.01403351,  0.01712859,  0.24781691, ...,  0.00516383,
         0.00604648,  0.01362891],
       ..., 
       [-0.00509533,  0.02282177,  0.00516383, ...,  0.34171359,
         0.02390086, -0.00866986],
       [ 0.00639793,  0.00047733,  0.00604648, ...,  0.02390086,
         0.28155033,  0.00398663],
       [ 0.00485253,  0.01061766,  0.01362891, ..., -0.00866986,
         0.00398663,  0.24200177]])