In [1]:
%pylab inline

import networkx as nx
import scipy.sparse
from sklearn.datasets import make_sparse_spd_matrix

import regain; reload(regain)
from regain.datasets import is_pos_def, is_pos_semidef
from regain.datasets import generate_ma_xue_zou
from regain.plot import plot_graph_with_latent_variables

Populating the interactive namespace from numpy and matplotlib


In [2]:
n_dim_latent = 2
n_dim_observed = 10

In [3]:
A = np.eye(5)
is_pos_def(A)

True

In [4]:
K_HO = np.zeros((n_dim_latent, n_dim_observed))
for i in range(n_dim_latent):
    percentage = int(n_dim_observed * 0.8)
    indices = np.random.randint(0, high=n_dim_observed, size=percentage)
    K_HO[i, indices] = np.random.rand(percentage)#*0.12

In [5]:
eigs, U = np.linalg.eigh(K_HO.T.dot(K_HO))
L = np.linalg.multi_dot((U, np.diag(1.0 + np.random.rand(n_dim_observed)), U.T))
# d = np.diag(L).reshape(1, L.shape[0])
# d = 1. / np.sqrt(d)

# L *= d
# L *= d.T

In [6]:
is_pos_semidef(L)

True

In [7]:
np.linalg.eigvals(L)

array([ 1.06137459,  1.08110023,  1.29312782,  1.78184825,  1.966272  ,
        1.91343537,  1.88577284,  1.90138111,  1.59554238,  1.37976814])

In [8]:
theta = np.diag(np.ones(n_dim_observed))
for i in range(n_dim_observed-1):
    l = list(np.arange(i+1,n_dim_observed))
    indices = np.random.choice(l, 2)
    theta[i, indices] = 0.25
    theta[indices, i] = 0.25
    

theta += np.diag(np.sum(L, axis=1))

theta_observed = theta -  L #? che si fa
theta_observed

array([[  1.11203300e+00,  -9.48605711e-02,  -7.94080688e-03,
         -1.71521013e-17,  -5.70773313e-17,  -5.70398703e-03,
          1.62446921e-01,   2.40116117e-01,   1.62014764e-01,
         -6.81054323e-02],
       [ -9.48605711e-02,   1.55145364e+00,   3.71996507e-02,
         -2.02140257e-16,   1.34893946e-16,  -7.09394784e-03,
          1.61819965e-01,   1.56052549e-03,   2.16523735e-02,
         -1.71731640e-01],
       [ -7.94080688e-03,   3.71996507e-02,   1.28848622e+00,
          7.80072573e-18,   2.50000000e-01,  -2.64222990e-02,
          2.15824699e-01,  -2.36623579e-01,  -5.44088405e-02,
          3.38849560e-02],
       [ -1.71521013e-17,  -2.02140257e-16,   7.80072573e-18,
          1.00184308e+00,  -1.84308462e-03,  -1.72542104e-17,
          9.89961748e-17,   2.50000000e-01,   2.50000000e-01,
         -5.35126892e-17],
       [ -5.70773313e-17,   1.34893946e-16,   2.50000000e-01,
         -1.84308462e-03,   1.00184308e+00,   1.90795272e-17,
          1.82866753e-16

In [9]:
# d = np.diag(theta_observed).reshape(1, theta_observed.shape[0])
# d = 1. / np.sqrt(d)

# theta_observed *= d
# theta_observed *= d.T

In [10]:
is_pos_def(theta_observed)

True

In [11]:
np.linalg.inv(theta_observed)

array([[  1.00322494e+00,   8.93236985e-02,  -4.10707857e-02,
          9.66461244e-02,   4.55988289e-02,   6.32286053e-02,
         -1.03110479e-01,  -2.46012644e-01,  -1.40948192e-01,
          1.24133334e-01],
       [  8.93236985e-02,   6.88420590e-01,   1.92986895e-02,
         -9.51622677e-03,  -1.66318022e-03,  -4.93959420e-02,
         -2.06848545e-01,   5.08266664e-02,  -1.27038639e-02,
          1.57103701e-01],
       [ -4.10707857e-02,   1.92986895e-02,   9.84721937e-01,
         -1.44687816e-01,  -2.83151861e-01,  -1.18549927e-01,
         -4.33720059e-01,   4.28824149e-01,   1.48906311e-01,
          2.92207104e-02],
       [  9.66461244e-02,  -9.51622677e-03,  -1.44687816e-01,
          1.17047667e+00,   1.02237693e-01,   1.42163590e-01,
          2.27876662e-01,  -4.33394569e-01,  -2.56387537e-01,
          1.88982615e-03],
       [  4.55988289e-02,  -1.66318022e-03,  -2.83151861e-01,
          1.02237693e-01,   1.13028716e+00,   3.49465597e-02,
          1.53270551e-01

In [12]:
from regain import datasets; reload(datasets)
thetas, thetas_obs, ells = datasets.generate2()

In [13]:
thetas

[array([[ 2.1410214 ,  0.25      ,  0.25      ],
        [ 0.25      ,  2.13022589,  0.25      ],
        [ 0.25      ,  0.25      ,  2.54737567]]),
 array([[ 2.37989616,  0.83997409, -0.80848635],
        [ 0.83997409,  2.11011604, -0.80071044],
        [-0.80848635, -0.80071044,  2.36353512]]),
 array([[ 3.66995761, -0.75662653, -0.75794589],
        [-0.75662653,  3.50658168,  0.64841009],
        [-0.75794589,  0.64841009,  3.672023  ]]),
 array([[ 3.09640672,  0.77307485,  0.21886604],
        [ 0.77307485,  2.36730331,  0.37505435],
        [ 0.21886604,  0.37505435,  3.04274355]]),
 array([[ 2.75334949, -0.75748817,  0.44984055],
        [-0.75748817,  3.45084319, -0.43239645],
        [ 0.44984055, -0.43239645,  2.86002152]]),
 array([[ 3.73254183,  0.68695161, -0.65336949],
        [ 0.68695161,  3.70352177, -0.62783152],
        [-0.65336949, -0.62783152,  3.75162239]]),
 array([[ 3.80758932, -0.77290174,  0.10270662],
        [-0.77290174,  3.56207847, -0.2477283 ],
        

In [14]:
b = np.random.rand(1, 5)
es, Q = np.linalg.eigh(b.T.dot(b))  # Q random

b = np.random.rand(1, 5)
es, R = np.linalg.eigh(b.T.dot(b))  # Q random

In [65]:
start_sigma = np.random.rand(5) + 1
start_lamda = np.zeros(5)
idx = np.random.randint(5, size=2)
start_lamda[idx] = np.random.rand(2)

Ks = []
Ls = []
Kobs = []

for i in range(4):
    K = np.linalg.multi_dot((Q, np.diag(start_sigma), Q.T))
    L = np.linalg.multi_dot((R, np.diag(start_lamda), R.T))
    
    K[np.abs(K) < 1e-1] = 0
 
    assert is_pos_def(K - L)
    assert is_pos_semidef(L)
    
    start_sigma += 1 + np.random.rand(5)
    start_lamda[idx] += np.random.rand(2) * 2 - 1
    start_lamda = np.maximum(start_lamda, 0)

    print start_lamda
    
    Ks.append(K)
    Ls.append(L)
    Kobs.append(K - L)

[ 0.  0.  0.  0.  0.]
[ 0.  0.  0.  0.  0.]
[ 0.          0.          0.          0.          0.53780231]
[ 0.  0.  0.  0.  0.]


In [66]:
reload(datasets)

<module 'regain.datasets' from '/home/fede/src/slipguru/regain/regain/datasets.pyc'>

In [72]:
ll = map(np.linalg.inv, Kobs)
map(datasets.normalize_matrix, ll);

In [62]:
data_list = [np.random.multivariate_normal(np.zeros(5), l, size=50) for l in ll]

In [63]:
from regain.admm import latent_time_graph_lasso_, time_graph_lasso_
K, L, S = latent_time_graph_lasso_.time_latent_graph_lasso(data_list, verbose=1)
# K, S = time_graph_lasso_.time_graph_lasso(data_list, verbose=1)

obj: 861.9435, rnorm: 2.8564, snorm: 5.7362,eps_pri: 0.0588, eps_dual: 0.0300
obj: 862.0042, rnorm: 1.1571, snorm: 1.5526,eps_pri: 0.0649, eps_dual: 0.0401
obj: 861.8951, rnorm: 0.8003, snorm: 1.1858,eps_pri: 0.0719, eps_dual: 0.0437
obj: 861.9060, rnorm: 0.7054, snorm: 1.0267,eps_pri: 0.0781, eps_dual: 0.0462
obj: 862.0081, rnorm: 0.7179, snorm: 0.9220,eps_pri: 0.0841, eps_dual: 0.0481
obj: 862.1194, rnorm: 0.8520, snorm: 0.7651,eps_pri: 0.0907, eps_dual: 0.0494
obj: 862.1972, rnorm: 1.0243, snorm: 0.5380,eps_pri: 0.0963, eps_dual: 0.0509
obj: 862.5128, rnorm: 1.1295, snorm: 0.2723,eps_pri: 0.0993, eps_dual: 0.0539
obj: 863.4442, rnorm: 1.0765, snorm: 0.2402,eps_pri: 0.0992, eps_dual: 0.0581
obj: 865.0322, rnorm: 0.8493, snorm: 0.3843,eps_pri: 0.0961, eps_dual: 0.0621
obj: 866.5272, rnorm: 0.5217, snorm: 0.4783,eps_pri: 0.0915, eps_dual: 0.0649
obj: 867.2723, rnorm: 0.2940, snorm: 0.4671,eps_pri: 0.0866, eps_dual: 0.0662
obj: 867.4627, rnorm: 0.3265, snorm: 0.3654,eps_pri: 0.0844, eps

In [57]:
K[np.abs(K) < 1e-2] = 0

In [58]:
Kcopy = K.copy()
Kcopy[:, np.arange(K.shape[1]), np.arange(K.shape[1])] = 0
Kscopy = np.array(Ks).copy()
Kscopy[:, np.arange(K.shape[1]), np.arange(K.shape[1])] = 0

np.linalg.norm(np.array(Kscopy) - Kcopy)

1.0537628406557296